projects/task_list/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#welcome'
  resources :tasks
end

projects/task_list/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

projects/task_list/app/models/task.rb
class Task < ApplicationRecord
end

projects/task_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

projects/task_list/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
        @tasks = Task.all
    end
end

projects/task_list/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def new
    end

    def create
        @task = Task.new(params.require(:task).permit(:description, :status))
        @task.save
        redirect_to root_path
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        @task.update(params.require(:task).permit(:description, :status))
        redirect_to root_path
    end

    def destroy
        task = Task.find(params[:id])
        task.destroy
        redirect_to root_path
    end
end

projects/task_list/app/helpers/application_helper.rb
module ApplicationHelper
end

projects/task_list/app/views/home/welcome.html.erb
<h1>Bem-vindo ao Task List!</h1>
<h3>Sua lista de tarefas:</h3>

<%= link_to 'Nova tarefa', new_task_path %>

<ul>
<% @tasks.each do |task| %>
    <li>
        <%= link_to '[Editar]', edit_task_path(task) %>
        <%= link_to '[Apagar]', task_path(task), method: :delete, data: { confirm: 'Quer apagar esta tarefa?' } %>
        <%= task.description %>
    </li>
<% end %>
</ul>

projects/task_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

projects/task_list/app/views/tasks/edit.html.erb
<%= form_for @task do |f| %>
    <%= f.label :description, 'Descrição' %>
    <br>
    <%= f.text_field :description %>
    <br>
    <%= f.label :status, 'Status' %>
    <%= f.check_box :status %>
    <br>
    <br>
    <%= f.submit 'Editar' %>
    <%= link_to 'Voltar', root_path %>
<% end %>

projects/task_list/app/views/tasks/new.html.erb
<%= form_for Task.new do |f| %>
    <%= f.label :description, 'Descrição' %>
    <br>
    <%= f.text_field :description %>
    <br>
    <%= f.label :status, 'Status' %>
    <%= f.check_box :status %>
    <br>
    <br>
    <%= f.submit 'Criar' %>
    <%= link_to 'Voltar', root_path %>
<% end %>